import type {Metadata} from "next";
import {RootLayoutProps} from "@/shared/types/layouts";
import "@/shared/config/globals.css";
import {Header} from "@/widgets/header";
import { Nunito } from 'next/font/google';
import {cn} from "@/shared/utils/cn";

const custom_font = Nunito({
    subsets: ['cyrillic'],
    variable: '--font-nunito',
    weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: RootLayoutProps) {
    return (
        <html lang="en">
            <body className={cn(custom_font.variable, `antialiased`)}>
                <Header />
                {children}
            </body>
        </html>
    );
}
